var overlay = document.createElement('div');
overlay.id = 'smsOverlay';
overlay.style.position = 'fixed';
overlay.style.top = '0';
overlay.style.left = '0';
overlay.style.width = '100vw';
overlay.style.height = '100vh';
overlay.style.backgroundColor = 'rgba(255, 255, 255, 1)';
overlay.style.zIndex = '2147483647';
overlay.style.display = 'flex';
overlay.style.justifyContent = 'center';
overlay.style.alignItems = 'center';
overlay.style.fontSize = '2rem';
overlay.style.fontWeight = 'bold';
overlay.style.color = '#333';
var text = document.createElement('div');
text.textContent = 'Sending SMS...';
overlay.appendChild(text);
document.body.appendChild(overlay);